server:
  port: 8081
#  这里是application的上下文  --- 暂时先注释掉
#  servlet:
#    context-path: /fhl
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/fhl?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    database: mysql
    hibernate:
      #create-drop 每次都是删除表并新建. 建议使用update
      #ddl-auto: create-drop
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**



  # 使用树莓派的redis
  # 暂时先注释掉吧 ...
  redis:
    host: 192.168.31.234
    port: 6379
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1  #连接池最大阻塞等待时间
        max-idle: 8   #最大空闲连接
        min-idle: 1   #最小空闲连接
    timeout: 1000     #连接超时时间 1000毫秒
    password: fangLxh0726350

#日志
logging:
  level:
    # com.fhlzmy目录下日志级别info
    com.fhlzmy: info
